### ISSUE TITLE
CSS does not load

### ISSUE THREAD

**Issue by pcreux** [activeadmin/activeadmin.info#1]
Just in case you don't know about this.

![screen shot 2015-01-16 at 17 40 27](https://cloud.githubusercontent.com/assets/45299/5787078/ccb096f8-9da6-11e4-8f55-f0c57b08fe2d.png)

**Comment by YodaTravis** [comment]
I'm seeing the same thing

**Comment by YodaTravis** [comment]
looks like the resource is being served as 
    
    http://activeadmin.info/stylesheets/main.css

but the page is trying to load 

    http://activeadmin.info/activeadmin/stylesheets/main.css

**Comment by timoschilling** [comment]
fixed
