### ISSUE TITLE
Customizing index page links returning 404

### ISSUE THREAD

**Issue by j1wilmot** [activeadmin/activeadmin.info#3]
The pages listed below are returning 404:
http://activeadmin.info/docs/3-index-pages/index-as-table.md
http://activeadmin.info/docs/3-index-pages/index-as-grid.md
http://activeadmin.info/docs/3-index-pages/index-as-block.md
http://activeadmin.info/docs/3-index-pages/index-as-blog.md

These are listed on http://activeadmin.info/docs/3-index-pages.html

Thanks!

**Comment by timoschilling** [comment]
THX
